print("Welcome to the Band Name Generator.")
print("What's name of the city you grew up in?")
first = input()
print("What's your pet's name?")
second = input()
print("Your band name could be " + first + " " + second)